### ISSUE TITLE
Call to undefined method Encore\Chartjs\Chartjs::boot() 

### ISSUE THREAD

**Issue by yljphp** [laravel-admin-extensions/chartjs#2]
![image](https://user-images.githubusercontent.com/8953279/46928542-a6029580-d06d-11e8-9bbc-0fe5b74c018d.png)

**Comment by stone009** [comment]
我也遇到这个问题了，怀疑是laravel-admin 版本的问题吧。我的版本是：1.5.15
之前用 1.5.7 安装就没出现这个问题。

你解决了这个问题了吗？

**Comment by CanonNr** [comment]
同问题

**Comment by zhuwenbo1992** [comment]
同问如何解决

**Comment by kunrui** [comment]
有人知道怎么解决？

**Comment by yljphp** [comment]
已经解决，需要更新laravel-admin 版本
